export const SET_NUMBER_OF_PLAYERS = `SET_NUMBER_OF_PLAYERS`;
export const SET_WARNING_TRUE = `SET_WARNING_TRUE`;
export const SET_WARNING_FALSE = "SET_WARNING_FALSE";
export const START_CHANGE_RANDOMLY_DATA_TABLE = `START_CHANGE_RANDOMLY_DATA_TABLE`;
